---
- name: restart all agents
  command: "{{item}} restart"
  with_fileglob:
   - /etc/init.d/go-agent?*

- name: restart go-server
  sudo: yes
  shell: "/etc/init.d/go-server restart"
  notify:
     - ensure go-server running

- name: ensure go-server running
  wait_for: port={{ GOCD_SERVER_PORT }} timeout=180 delay=10

- name: restart firewalld
  sudo: yes
  service: name=firewalld state=restarted
