---
- name: restart all go services
  shell: ls -1 /etc/default/go-agent?* /etc/default/go-server
  register: go_services
  notify:
     - restart go service
     - ensure go-server running

- name: restart all agents
  shell: ls -1 /etc/default/go-agent?*
  register: go_services
  notify:
     - restart go service

- name: restart go service
  shell: /etc/init.d/{{ item | basename }} restart
  with_items: go_services.stdout_lines
  sudo: yes

- name: restart go-server
  sudo: yes
  shell: /etc/init.d/go-server restart
  notify:
     - ensure go-server running

- name: ensure go-server running
  wait_for: port={{ GOCD_SERVER_PORT }} timeout=180 delay=10

- name: restart firewalld
  sudo: yes
  system: name=firewalld state=restarted
